### ISSUE TITLE
Thank you very much!!

### ISSUE THREAD

**Issue by pga42** [Sor3nt/manhunt-toolkit#14]
For now I simply wanted to thank you for your work. 

I noticed that everything related to your account at projectmanhunt appeared as "gone" recently. It isn't of my concern why you did it (in case you are actually responsible of this), but just wanted to express my support for your excellent work and that i have been following the progress on this tool since your first post about it in that site. 

Hope you publish the final result or more progress here whenever you're ready of course.

I have already used the tool and haven't found bugs or issues so far, but if i find something i'll surely communicate it. 

Cheers.

**Comment by Sor3nt** [comment]
Thank you for the feedback, I do my best to create good tools for us :)

It was not a Administrator choice, I leaved the place by my self because of all the hate speech and non existent moderation.

I try always to release a bug free version but its not always possible by the given rockstar magic :)

I still work on the tools, currently I am near finished with the MLS Bytecode compiler and yes I will release it here and also on http://gtaforums.com (i am not active there yet)

I am happy that my tools works for you, when ever you found bugs or want a feature, just raising an issue in GitHub and I will take it over.

Have a nice day

**Comment by pga42** [comment]
You're very welcome, your intentions about offering reasonably good quality work or results can be noted in the product itself, haha, and that is remarkable of course!!
 
About your reasons for leaving, yeah, that's what i thought and i respect you about it.

Well, even considering the rockstar magic, you've proven to posess magic of your own which is a worthy rival of theirs, and in any case, a tool with bugs is always better than nothing, but still, i absolutely understand  your desire of completion or maybe perfection? haha either way, that's it.

It's great that you keep working on this, as well as there having been even more progress, and as i mentioned, i look forward for the final release of the tool here and anywhere else :P.

If i have an issue, i'll surely raise it here.

Have an excellent day

**Comment by Sor3nt** [comment]
Release is here, i close this issue :)
