### ISSUE TITLE
Possible support for converting PNG to PSP/PS2 image format?

### ISSUE THREAD

**Issue by santiago046** [Sor3nt/manhunt-toolkit#33]
_Better to create a new issue to discuss this._

The MH2's PSP/PS2 version probably uses TIM2 image format — or at least its compression method — like most PSP/PS2 games. Maybe [this](https://wiki.xentax.com/index.php/TM2_TIM2) can help or just tells the decompression of it? I also found this [repository](https://github.com/jw0z96/tim-cli) about the first version.

**Comment by Sor3nt** [comment]
so you are looking actual for psp image packing support. not just a converter

since i moved the image backend to imagemagick, there is hope, it supports TIM2.
i will check this out

**Comment by santiago046** [comment]
Yes. ImageMagick supports only reading of TM2.

**Comment by Sor3nt** [comment]
just checked your links, MHT can decode PS2/PSP textures but we are looking for a encoder, there is for sure some open source tools which can create tm2.

will check it

**Comment by santiago046** [comment]
In the leaked [PS2 SDKs](https://archive.org/download/ps2_sdks), you will find some resources about TM2 (tim2*).

**Comment by Sor3nt** [comment]
checked some resources, also the SDK. it would be a little nightmare to create support for image to tm2.
i will not add these in near future. MHT is primary for PC and (unpacking) support for other platforms so we can port to PC.

something like this is perfect https://github.com/ImageMagick/ImageMagick/blob/b939fa13bc23169514cc4aa34ceaf87fdccd4c20/coders/tim2.c

i looked around and someone said there was a unmerged tim2.c with packing support but was rejected because of copyrights... can not fine it -.-

If you can come up with a write tm2 class then i may look again to it.
